### ISSUE TITLE
Copied content

### ISSUE THREAD

**Issue by 0xdabbad00** [carlospolop/hacktricks-cloud#15]
There appear to be a number of pages of content which are directly copied from https://frichetten.com.  Did you get permission to copy that content?  This seems inappropriate to copy so much content directly like this.

**Comment by carlospolop** [comment]
Hi @0xdabbad00,
I appreciate your concern. This is a topic I discussed months ago with the author of such blog. As far as I know everything is OK from his side (at least I did the changes we talked about and notified him and I haven't had new comments from him).
If you know it's not, please, feel free to tell him that he can DM me in twitter whenever he wants and tell me his concerns.

In any case, I have modified that HackTricks blog post to explain the techniques with my own words instead of being copying them from the source. Hopefully this was something you were looking for.

Also, let me attach a link to the recently added HackTricks project values: https://book.hacktricks.xyz/welcome/hacktricks-values-and-faq
